---
# tasks file for tripleo_overcloud_raid_create
- name: Set overcloud raid create facts
  set_fact:
    _raid_cmd: >-
      {{ tripleo_overcloud_raid_create_os_cloud | ternary('', "source " ~ tripleo_overcloud_raid_create_rc_file ~ "; ") }}
      {{ openstack_bin }} overcloud raid create
      {{ tripleo_overcloud_raid_create_nodes | tripleo.operator.shell_arg_list('--node') }}
      {{ tripleo_overcloud_raid_create_configuration }}
      {{ tripleo_overcloud_raid_create_log_output | ternary((">" ~ tripleo_overcloud_raid_create_log), '') }}
      {{ tripleo_overcloud_raid_create_log_combine | ternary("2>&1", '') }}
    _raid_env:
      OS_CLOUD: "{{ tripleo_overcloud_raid_create_os_cloud }}"

- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ tripleo_overcloud_raid_create_log }}"
  when: tripleo_overcloud_raid_create_log_output|bool

- name: Show debug information
  when: tripleo_overcloud_raid_create_debug|bool
  block:
    - name: Show the command
      debug:
        var: _raid_cmd

    - name: Show the environment
      debug:
        var: _raid_env

- name: Write reproducer script
  tripleo_shell_script:
    dest: "{{ tripleo_overcloud_raid_create_home_dir }}/tripleo_overcloud_raid_create.sh"
    shell_command: "{{ _raid_cmd }}"
    shell_environment: "{{ _raid_env }}"
  when: tripleo_overcloud_raid_create_generate_scripts|bool

- name: overcloud raid create
  shell: "{{ _raid_cmd }}"  # noqa 305
  environment: "{{ _raid_env }}"
  args:
    executable: /bin/bash
    chdir: "{{ tripleo_overcloud_raid_create_home_dir }}"
    warn: false
  register: tripleo_overcloud_raid_create_result
  async: "{{ tripleo_overcloud_raid_create_timeout }}"
  poll: "{{ tripleo_overcloud_raid_create_poll }}"
  changed_when: false
  when:
    - not ansible_check_mode|bool
    - not tripleo_overcloud_raid_create_generate_scripts_only|bool

- name: Set output fact
  when:
    - tripleo_overcloud_raid_create_result.stdout is defined
  set_fact:
    tripleo_overcloud_raid_create_output: "{{ tripleo_overcloud_raid_create_result.stdout }}"
