---
# tasks file for tripleo_overcloud_export
- name: Setup overcloud export facts
  set_fact:
    _export_cmd: >-
      {{ tripleo_overcloud_export_os_cloud | ternary('', "source " ~ tripleo_overcloud_export_rc_file ~ "; ") }}
      {{ openstack_bin }} overcloud export
      {{ tripleo_overcloud_export_stack | ternary('--stack ' ~ tripleo_overcloud_export_stack, '') }}
      {{ tripleo_overcloud_export_output_file | ternary('--output-file ' ~ tripleo_overcloud_export_output_file, '') }}
      {{ tripleo_overcloud_export_force_overwrite | ternary('--force-overwrite', '') }}
      {{ tripleo_overcloud_export_config_download_dir | ternary('--config-download-dir ' ~ tripleo_overcloud_export_config_download_dir, '') }}
      {{ tripleo_overcloud_export_no_password_excludes | ternary('--no-password-excludes', '') }}
    _export_env:
      OS_CLOUD: "{{ tripleo_overcloud_export_os_cloud }}"

- name: Show debug information
  when: tripleo_overcloud_export_debug|bool
  block:
    - name: Show the overcloud export command
      debug:
        var: _export_cmd

    - name: Show the overcloud export environment
      debug:
        var: _export_env

- name: Write reproducer script
  tripleo_shell_script:
    dest: "{{ tripleo_overcloud_export_home_dir }}/tripleo_overcloud_export.sh"
    shell_command: "{{ _export_cmd }}"
    shell_environment: "{{ _export_env }}"
  when: tripleo_overcloud_export_generate_scripts|bool

- name: Overcloud export
  shell: "{{ _export_cmd }}"  # noqa 305
  environment: "{{ _export_env }}"
  args:
    executable: /bin/bash
    chdir: "{{ tripleo_overcloud_export_home_dir }}"
  register: tripleo_overcloud_export_result
  changed_when: false
  when:
    - not ansible_check_mode|bool
    - not tripleo_overcloud_export_generate_scripts_only|bool

- name: Set output fact
  when:
    - tripleo_overcloud_export_result.stdout is defined
  set_fact:
    tripleo_overcloud_export_output: "{{ tripleo_overcloud_export_result.stdout }}"
