---
# tasks file for tripleo_overcloud_node_delete
- name: Setup overcloud node delete command
  set_fact:
    _delete_cmd: >-
      {{ tripleo_overcloud_node_delete_os_cloud | ternary('', "source " ~ tripleo_overcloud_node_delete_rc_file ~ "; ") }}
      {{ openstack_bin }} overcloud node delete
      {{ tripleo_overcloud_node_delete_nodes | join(' ') }}
      {{ tripleo_overcloud_node_delete_baremetal_deployment | ternary('--baremetal-deployment ' ~ tripleo_overcloud_node_delete_baremetal_deployment, '') }}
      {{ tripleo_overcloud_node_delete_stack | ternary('--stack ' ~ tripleo_overcloud_node_delete_stack, '') }}
      {{ tripleo_overcloud_node_delete_templates | ternary('--templates ' ~ tripleo_overcloud_node_delete_templates, '') }}
      {{ tripleo_overcloud_node_delete_environment_file | tripleo.operator.shell_arg_list('--environment-file') }}
      {{ tripleo_overcloud_node_delete_timeout | ternary('--timeout ' ~ tripleo_overcloud_node_delete_timeout, '') }}
      {{ tripleo_overcloud_node_delete_yes | ternary('--yes', '') }}

    _delete_env:
      OS_CLOUD: "{{ tripleo_overcloud_node_delete_os_cloud }}"

- name: Show debug information
  when: tripleo_overcloud_node_delete_debug|bool
  block:
    - name: Show the node delete command
      debug:
        var: _delete_cmd

    - name: Show the node delete environment
      debug:
        var: _delete_env

- name: Write reproducer script
  tripleo_shell_script:
    dest: "{{ tripleo_overcloud_node_delete_home_dir }}/tripleo_overcloud_node_delete.sh"
    shell_command: "{{ _delete_cmd }}"
    shell_environment: "{{ _delete_env }}"
  when: tripleo_overcloud_node_delete_generate_scripts|bool

- name: Delete node
  shell: "{{ _delete_cmd }}"  # noqa 305
  environment: "{{ _delete_env }}"
  args:
    executable: /bin/bash
    chdir: "{{ tripleo_overcloud_node_delete_home_dir }}"
  register: tripleo_overcloud_node_delete_result
  changed_when: true
  when:
    - not ansible_check_mode|bool
    - not tripleo_overcloud_node_delete_generate_scripts_only|bool

- name: Set output fact
  when:
    - tripleo_overcloud_node_delete_result.stdout is defined
  set_fact:
    tripleo_overcloud_node_delete_output: "{{ tripleo_overcloud_node_delete_result.stdout }}"
