---
# tasks file for tripleo_overcloud_container_image_prepare
- name: Set overcloud container image prepare facts
  set_fact:
    _prepare_cmd: >-
      {{ openstack_bin }} overcloud container image prepare
      {{ tripleo_overcloud_container_image_prepare_template_file | ternary('--template-file $PREPARE_TEMPLATE_FILE', '') }}
      {{ tripleo_overcloud_container_image_prepare_push_destination | ternary('--push-destination $PREPARE_PUSH_DESTINATION', '') }}
      {{ tripleo_overcloud_container_image_prepare_tag | ternary('--tag $PREPARE_TAG', '') }}
      {{ tripleo_overcloud_container_image_prepare_tag_from_label | ternary('--tag-from-label $PREPARE_TAG_FROM_LABEL', '') }}
      {{ tripleo_overcloud_container_image_prepare_namespace | ternary('--namespace $PREPARE_NAMESPACE', '') }}
      {{ tripleo_overcloud_container_image_prepare_prefix | ternary('--prefix $PREPARE_PREFIX', '') }}
      {{ tripleo_overcloud_container_image_prepare_suffix | ternary('--suffix $PREPARE_SUFFIX', '') }}
      {{ tripleo_overcloud_container_image_prepare_set | tripleo.operator.shell_arg_list('--set') }}
      {{ tripleo_overcloud_container_image_prepare_excludes | tripleo.operator.shell_arg_list('--exclude') }}
      {{ tripleo_overcloud_container_image_prepare_includes | tripleo.operator.shell_arg_list('--include') }}
      {{ tripleo_overcloud_container_image_prepare_output_images_file | ternary('--output-images-file $PREPARE_OUTPUT_IMAGES_FILE', '') }}
      {{ tripleo_overcloud_container_image_prepare_environment_files | tripleo.operator.shell_arg_list('--environment-file') }}
      {{ tripleo_overcloud_container_image_prepare_environment_directory | ternary('--environment-directory $PREPARE_ENVIRONMENT_DIR', '') }}
      {{ tripleo_overcloud_container_image_prepare_output_env_file | ternary('--output-env-file $PREPARE_OUTPUT_ENV_FILE', '') }}
      {{ tripleo_overcloud_container_image_prepare_roles_file | ternary('--roles-file $PREPARE_ROLES_FILE', '') }}
      {{ tripleo_overcloud_container_image_prepare_modify_role | ternary('--modify-role $PREPARE_MODIFY_ROLE', '') }}
      {{ tripleo_overcloud_container_image_prepare_modify_vars | ternary('--modify-vars $PREPARE_MODIFY_VARS', '') }}
      {{ tripleo_overcloud_container_image_prepare_log_output | ternary((">" ~ tripleo_overcloud_container_image_prepare_log), '') }}
      {{ tripleo_overcloud_container_image_prepare_log_combine | ternary("2>&1", '') }}
    _prepare_env:
      PREPARE_TEMPLATE_FILE: "{{ tripleo_overcloud_container_image_prepare_template_file | quote }}"
      PREPARE_PUSH_DESTINATION: "{{ tripleo_overcloud_container_image_prepare_push_destination | quote }}"
      PREPARE_TAG: "{{ tripleo_overcloud_container_image_prepare_tag | quote }}"
      PREPARE_TAG_FROM_LABEL: "{{ tripleo_overcloud_container_image_prepare_tag_from_label | quote }}"
      PREPARE_NAMESPACE: "{{ tripleo_overcloud_container_image_prepare_namespace | quote }}"
      PREPARE_PREFIX: "{{ tripleo_overcloud_container_image_prepare_prefix | quote }}"
      PREPARE_SUFFIX: "{{ tripleo_overcloud_container_image_prepare_suffix | quote }}"
      PREPARE_OUTPUT_IMAGES_FILE: "{{ tripleo_overcloud_container_image_prepare_output_images_file | quote }}"
      PREPARE_ENVIRONMENT_DIR: "{{ tripleo_overcloud_container_image_prepare_environment_directory | quote }}"
      PREPARE_OUTPUT_ENV_FILE: "{{ tripleo_overcloud_container_image_prepare_output_env_file | quote }}"
      PREPARE_ROLES_FILE: "{{ tripleo_overcloud_container_image_prepare_roles_file | quote }}"
      PREPARE_MODIFY_ROLE: "{{ tripleo_overcloud_container_image_prepare_modify_role | quote }}"
      PREPARE_MODIFY_VARS: "{{ tripleo_overcloud_container_image_prepare_modify_vars | quote }}"


- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ tripleo_overcloud_container_image_prepare_log }}"
  when: tripleo_overcloud_container_image_prepare_log_output|bool

- name: Show debug information
  when: tripleo_overcloud_container_image_prepare_debug|bool
  block:
    - name: Show the command
      debug:
        var: _prepare_cmd

    - name: Show the environment
      debug:
        var: _prepare_env

- name: Write reproducer script
  tripleo_shell_script:
    dest: "{{ tripleo_overcloud_container_image_prepare_home_dir }}/tripleo_overcloud_container_image_prepare.sh"
    shell_command: "{{ _prepare_cmd }}"
    shell_environment: "{{ _prepare_env }}"
  when: tripleo_overcloud_container_image_prepare_generate_scripts|bool

- name: Run overcloud container image prepare
  shell: "{{ _prepare_cmd }}"  # noqa 305
  environment: "{{ _prepare_env }}"
  args:
    executable: /bin/bash
    chdir: "{{ tripleo_overcloud_container_image_prepare_home_dir }}"
    warn: false
  register: tripleo_overcloud_container_image_prepare_result
  async: "{{ tripleo_overcloud_container_image_prepare_timeout }}"
  poll: "{{ tripleo_overcloud_container_image_prepare_poll }}"
  changed_when: false
  when:
    - not ansible_check_mode|bool
    - not tripleo_overcloud_container_image_prepare_generate_scripts_only|bool

- name: Set output fact
  when:
    - tripleo_overcloud_container_image_prepare_result.stdout is defined
  set_fact:
    tripleo_overcloud_container_image_prepare_output: "{{ tripleo_overcloud_container_image_prepare_result.stdout }}"
