---
- name: Setup validator group info facts
  set_fact:
    _validator_group_info_cmd: >-
      {{ openstack_bin }} tripleo validator group info

- name: Show debug information
  when:
    tripleo_validator_group_info_debug|bool
  block:
    - name: Show validator group info command
      debug:
        var: _validator_group_info_cmd

- name: Show validation group info
  shell: "{{ _validator_group_info_cmd }}"
  register: tripleo_validator_group_info_result
  changed_when: true
