---
# tasks file for tripleo_overcloud_ffwd_upgrade_prepare
- name: Setup overcloud ffwd-upgrade prepare facts
  set_fact:
    _upgrade_prepare_cmd: >-
      {{ tripleo_overcloud_ffwd_upgrade_prepare_os_cloud | ternary('', "source " ~ tripleo_overcloud_ffwd_upgrade_prepare_rc_file ~ "; ") }}
      {{ openstack_bin }} overcloud ffwd-upgrade prepare
      {{ tripleo_overcloud_ffwd_upgrade_prepare_templates | ternary('--templates $FFWD_TEMPLATES', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_stack | ternary('--stack $FFWD_STACK', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_timeout_arg | ternary('--timeout $FFWD_TIMEOUT_ARG', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_libvirt_type | ternary('--libvirt-type $FFWD_LIBVIRT_TYPE', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_ntp_server | ternary('--ntp-server $FFWD_NTP_SERVER', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_no_proxy | ternary('--no-proxy $FFWD_NO_PROXY', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_overcloud_ssh_user | ternary('--overcloud-ssh-user $FFWD_OC_SSH_USER', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_overcloud_ssh_key | ternary('--overcloud-ssh-key $FFWD_OC_SSH_KEY', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_overcloud_ssh_network | ternary('--overcloud-ssh-network $FFWD_OC_SSH_NETWORK', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_overcloud_ssh_enable_timeout | ternary('--overcloud-ssh-enable-timeout $FFWD_OC_SSH_ENABLE_TIMEOUT', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_overcloud_ssh_port_timeout | ternary('--overcloud-ssh-port-timeout $FFWD_OC_SSH_PORT_TIMEOUT', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_environment_files | tripleo.operator.shell_arg_list(parameter='-e') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_environment_dirs | tripleo.operator.shell_arg_list(parameter='--environment-directory') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_roles_file | ternary('-r $FFWD_ROLES_FILE', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_networks_file | ternary('-n $FFWD_NETWORKS_FILE', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_plan_environment_file | ternary('-p $FFWD_PLAN_ENV_FILE', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_no_cleanup | ternary('--no-cleanup', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_validation_errors_nonfatal | ternary('--validation-errors-nonfatal', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_validation_warnings_fatal | ternary('--validation-warnings-fatal', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_disable_validations | ternary('--disable-validations', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_inflight_validations | ternary('--inflight-validations', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_dry_run | ternary('--dry-run', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_run_validations | ternary('--run-validations', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_skip_postconfig | ternary('--skip-postconfig', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_force_postconfig | ternary('--force-postconfig', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_skip_deploy_identifier | ternary('--skip-deploy-identifier', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_answers_file | ternary('--answers-file $FFWD_ANSWERS_FILE', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_disable_password_generation | ternary('--disable-password-generation', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_deployed_server | ternary('--deployed-server', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_config_download | ternary('--config-download', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_no_config_download | ternary('--no-config-download', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_output_dir | ternary('--output-dir $FFWD_OUTPUT_DIR', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_override_ansible_cfg | ternary('--override-ansible-cfg $FFWD_OVERRIDE_ANSIBLE_CFG', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_config_download_timeout | ternary('--config-download-timeout $FFWD_CONFIG_DOWNLOAD_TIMEOUT', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_baremetal_deployment | ternary('--baremetal-deployment $FFWD_BAREMETAL_DEPLOYMENT', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_yes | ternary('--yes', '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_log_output | ternary((">" ~ tripleo_overcloud_ffwd_upgrade_prepare_log), '') }}
      {{ tripleo_overcloud_ffwd_upgrade_prepare_log_combine | ternary("2>&1", '') }}
    _upgrade_prepare_env:
      FFWD_TEMPLATES: "{{ tripleo_overcloud_ffwd_upgrade_prepare_templates }}"
      FFWD_STACK: "{{ tripleo_overcloud_ffwd_upgrade_prepare_stack }}"
      FFWD_TIMEOUT_ARG: "{{ tripleo_overcloud_ffwd_upgrade_prepare_timeout_arg }}"
      FFWD_LIBVIRT_TYPE: "{{ tripleo_overcloud_ffwd_upgrade_prepare_libvirt_type }}"
      FFWD_NTP_SERVER: "{{ tripleo_overcloud_ffwd_upgrade_prepare_ntp_server }}"
      FFWD_NO_PROXY: "{{ tripleo_overcloud_ffwd_upgrade_prepare_no_proxy }}"
      FFWD_OC_SSH_USER: "{{ tripleo_overcloud_ffwd_upgrade_prepare_overcloud_ssh_user }}"
      FFWD_OC_SSH_KEY: "{{ tripleo_overcloud_ffwd_upgrade_prepare_overcloud_ssh_key }}"
      FFWD_OC_SSH_NETWORK: "{{ tripleo_overcloud_ffwd_upgrade_prepare_overcloud_ssh_network }}"
      FFWD_OC_SSH_ENABLE_TIMEOUT: "{{ tripleo_overcloud_ffwd_upgrade_prepare_overcloud_ssh_enable_timeout }}"
      FFWD_OC_SSH_PORT_TIMEOUT: "{{ tripleo_overcloud_ffwd_upgrade_prepare_overcloud_ssh_port_timeout }}"
      FFWD_ROLES_FILE: "{{ tripleo_overcloud_ffwd_upgrade_prepare_roles_file }}"
      FFWD_NETWORKS_FILE: "{{ tripleo_overcloud_ffwd_upgrade_prepare_networks_file }}"
      FFWD_PLAN_ENV_FILE: "{{ tripleo_overcloud_ffwd_upgrade_prepare_plan_environment_file }}"
      FFWD_ANSWERS_FILE: "{{ tripleo_overcloud_ffwd_upgrade_prepare_answers_file }}"
      FFWD_OUTPUT_DIR: "{{ tripleo_overcloud_ffwd_upgrade_prepare_output_dir }}"
      FFWD_OVERRIDE_ANSIBLE_CFG: "{{ tripleo_overcloud_ffwd_upgrade_prepare_override_ansible_cfg }}"
      FFWD_CONFIG_DOWNLOAD_TIMEOUT: "{{ tripleo_overcloud_ffwd_upgrade_prepare_config_download_timeout }}"
      FFWD_BAREMETAL_DEPLOYMENT: "{{ tripleo_overcloud_ffwd_upgrade_prepare_baremetal_deployment }}"
      OS_CLOUD: "{{ tripleo_overcloud_ffwd_upgrade_prepare_os_cloud }}"

- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ tripleo_overcloud_ffwd_upgrade_prepare_log }}"
  when: tripleo_overcloud_ffwd_upgrade_prepare_log_output|bool

- name: Show debug information
  when: tripleo_overcloud_ffwd_upgrade_prepare_debug|bool
  block:
    - name: Show the overcloud ffwd-upgrade prepare command
      debug:
        var: _upgrade_prepare_cmd

    - name: Show the overcloud ffwd-upgrade prepare environment
      debug:
        var: _upgrade_prepare_env

- name: Write reproducer script
  tripleo_shell_script:
    dest: "{{ tripleo_overcloud_ffwd_upgrade_prepare_home_dir }}/tripleo_overcloud_ffwd_upgrade_prepare.sh"
    shell_command: "{{ _upgrade_prepare_cmd }}"
    shell_environment: "{{ _upgrade_prepare_env }}"
  when: tripleo_overcloud_ffwd_upgrade_prepare_generate_scripts|bool

- name: overcloud ffwd-upgrade prepare
  shell: "{{ _upgrade_prepare_cmd }}"  # noqa 305
  environment: "{{ _upgrade_prepare_env }}"
  args:
    chdir: "{{ tripleo_overcloud_ffwd_upgrade_prepare_home_dir }}"
    warn: false
  register: tripleo_overcloud_ffwd_upgrade_prepare_result
  async: "{{ tripleo_overcloud_ffwd_upgrade_prepare_timeout }}"
  poll: "{{ tripleo_overcloud_ffwd_upgrade_prepare_poll }}"
  changed_when: false
  when:
    - not ansible_check_mode|bool
    - not tripleo_overcloud_ffwd_upgrade_prepare_generate_scripts_only|bool

- name: Set output fact
  when:
    - tripleo_overcloud_ffwd_upgrade_prepare_result.stdout is defined
  set_fact:
    tripleo_overcloud_ffwd_upgrade_prepare_output: "{{ tripleo_overcloud_ffwd_upgrade_prepare_result.stdout }}"
