---
# tasks file for _skeleton
- name: Set overcloud config download facts
  set_fact:
    _download_cmd: >-
      {{ tripleo_overcloud_config_download_os_cloud | ternary('', "source " ~ tripleo_overcloud_config_download_rc_file ~ "; ") }}
      {{ openstack_bin }} overcloud config download
      {{ tripleo_overcloud_config_download_name | ternary('--name $DOWNLOAD_NAME', '') }}
      {{ tripleo_overcloud_config_download_config_dir | ternary('--config-dir $DOWNLOAD_CONFIG_DIR', '') }}
      {{ tripleo_overcloud_config_download_config_type | ternary('--config-type $DOWNLOAD_CONFIG_TYPE', '') }}
      {{ tripleo_overcloud_config_download_no_preserve_config | ternary('--no-preserve-config', '') }}
      {{ tripleo_overcloud_config_download_log_output | ternary((">" ~ tripleo_overcloud_config_download_log), '') }}
      {{ tripleo_overcloud_config_download_log_combine | ternary("2>&1", '') }}
    _download_env:
      DOWNLOAD_NAME: "{{ tripleo_overcloud_config_download_name | quote }}"
      DOWNLOAD_CONFIG_DIR: "{{ tripleo_overcloud_config_download_config_dir | quote }}"
      DOWNLOAD_CONFIG_TYPE: "{{ tripleo_overcloud_config_download_config_type | quote }}"
      OS_CLOUD: "{{ tripleo_overcloud_config_download_os_cloud }}"


- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ tripleo_overcloud_config_download_log }}"
  when: tripleo_overcloud_config_download_log_output|bool

- name: Show debug information
  when: tripleo_overcloud_config_download_debug|bool
  block:
    - name: Show the command
      debug:
        var: _download_cmd

    - name: Show the environment
      debug:
        var: _download_env

- name: Write reproducer script
  tripleo_shell_script:
    dest: "{{ tripleo_overcloud_config_download_home_dir }}/tripleo_overcloud_config_download.sh"
    shell_command: "{{ _download_cmd }}"
    shell_environment: "{{ _download_env }}"
  when: tripleo_overcloud_config_download_generate_scripts|bool

- name: Run overcloud config download
  shell: "{{ _download_cmd }}"  # noqa 305
  environment: "{{ _download_env }}"
  args:
    executable: /bin/bash
    chdir: "{{ tripleo_overcloud_config_download_home_dir }}"
    warn: false
  register: tripleo_overcloud_config_download_result
  async: "{{ tripleo_overcloud_config_download_timeout }}"
  poll: "{{ tripleo_overcloud_config_download_poll }}"
  changed_when: false
  when:
    - not ansible_check_mode|bool
    - not tripleo_overcloud_config_download_generate_scripts_only|bool

- name: Set output fact
  when:
    - tripleo_overcloud_config_download_result.stdout is defined
  set_fact:
    tripleo_overcloud_config_download_output: "{{ tripleo_overcloud_config_download_result.stdout }}"
