---
- name: Converge
  hosts: all
  collections:
    - tripleo.operator
  vars:
    openstack_bin: echo
    tripleo_os_cloud: undercloud
    tripleo_undercloud_backup_become: false
    tripleo_undercloud_backup_debug: true
    tripleo_undercloud_backup_log_output: false
    tripleo_undercloud_backup_log_combine: false
    tripleo_undercloud_backup_poll: 1
  tasks:

    - name: "Include tripleo_undercloud_backup"
      include_role:
        name: "tripleo_undercloud_backup"

    - name: Check role
      assert:
        that:
          - tripleo_undercloud_backup_result.stdout == "undercloud backup"

    - name: Check parameter "tripleo_undercloud_backup_add_path"
      include_role:
        name: "tripleo_undercloud_backup"
      vars:
        tripleo_undercloud_backup_add_path:
          - /foo
          - /bar

    - name: Assert "tripleo_undercloud_backup_add_path"
      assert:
        that:
          - tripleo_undercloud_backup_result.stdout == "undercloud backup --add-path /foo --add-path /bar"

    - name: Check parameter "tripleo_undercloud_backup_exclude_path"
      include_role:
        name: "tripleo_undercloud_backup"
      vars:
        tripleo_undercloud_backup_exclude_path:
          - /home
          - /usr

    - name: Assert "tripleo_undercloud_backup_exclude_path"
      assert:
        that:
          - tripleo_undercloud_backup_result.stdout == "undercloud backup --exclude-path /home --exclude-path /usr"
