---
- name: Converge
  hosts: all
  collections:
    - tripleo.operator
  vars:
    openstack_bin: echo
    tripleo_os_cloud: undercloud
    tripleo_undercloud_backup_become: false
    tripleo_undercloud_backup_debug: true
    tripleo_undercloud_backup_log_output: false
    tripleo_undercloud_backup_log_combine: false
    tripleo_undercloud_backup_poll: 1
  tasks:

    - name: "Include tripleo_undercloud_backup"
      include_role:
        name: "tripleo_undercloud_backup"

    - name: Check role
      assert:
        that:
          - tripleo_undercloud_backup_result.stdout == "undercloud backup"

    - name: Check parameter "tripleo_undercloud_backup_add_path"
      include_role:
        name: "tripleo_undercloud_backup"
      vars:
        tripleo_undercloud_backup_add_path:
          - /foo
          - /bar

    - name: Assert "tripleo_undercloud_backup_add_path"
      assert:
        that:
          - tripleo_undercloud_backup_result.stdout == "undercloud backup --add-path /foo --add-path /bar"

    - name: Check parameter "tripleo_undercloud_backup_exclude_path"
      include_role:
        name: "tripleo_undercloud_backup"
      vars:
        tripleo_undercloud_backup_exclude_path:
          - /home
          - /usr

    - name: Assert "tripleo_undercloud_backup_exclude_path"
      assert:
        that:
          - tripleo_undercloud_backup_result.stdout == "undercloud backup --exclude-path /home --exclude-path /usr"


    - name: Check parameter "tripleo_undercloud_backup_init_rear"
      include_role:
        name: "tripleo_undercloud_backup"
      vars:
        tripleo_undercloud_backup_init: rear

    - name: Assert "tripleo_undercloud_backup_init_rear"
      assert:
        that:
          - tripleo_undercloud_backup_result.stdout == "undercloud backup --init rear"

    - name: Check parameter "tripleo_undercloud_backup_init_nfs"
      include_role:
        name: "tripleo_undercloud_backup"
      vars:
        tripleo_undercloud_backup_init: nfs

    - name: Assert "tripleo_undercloud_backup_init_nfs"
      assert:
        that:
          - tripleo_undercloud_backup_result.stdout == "undercloud backup --init nfs"

    - name: Check parameter "tripleo_undercloud_backup_setup_nfs"
      include_role:
        name: "tripleo_undercloud_backup"
      vars:
        tripleo_undercloud_backup_setup_nfs: true

    - name: Assert "tripleo_undercloud_backup_setup_nfs"
      assert:
        that:
          - tripleo_undercloud_backup_result.stdout == "undercloud backup --setup-nfs"

    - name: Check parameter "tripleo_undercloud_backup_setup_rear"
      include_role:
        name: "tripleo_undercloud_backup"
      vars:
        tripleo_undercloud_backup_setup_rear: true

    - name: Assert "tripleo_undercloud_backup_setup_rear"
      assert:
        that:
          - tripleo_undercloud_backup_result.stdout == "undercloud backup --setup-rear"

    - name: Check parameter "tripleo_undercloud_backup_setup_rear_extra_vars_file"
      include_role:
        name: "tripleo_undercloud_backup"
      vars:
        tripleo_undercloud_backup_setup_rear: true
        tripleo_undercloud_backup_extra_vars: /path/to/vars.yaml

    - name: Assert "tripleo_undercloud_backup_setup_rear_extra_vars_file"
      assert:
        that:
          - tripleo_undercloud_backup_result.stdout == "undercloud backup --setup-rear --extra-vars /path/to/vars.yaml"

    - name: Check parameter "tripleo_undercloud_backup_setup_rear_extra_vars_string"
      include_role:
        name: "tripleo_undercloud_backup"
      vars:
        tripleo_undercloud_backup_setup_rear: true
        tripleo_undercloud_backup_extra_vars: "{{ {'tripleo_backup_and_restore_nfs_server': '192.168.24.1'} | to_json }}"

    - name: Assert "tripleo_undercloud_backup_setup_rear_extra_vars_string"
      vars:
        tripleo_undercloud_backup_extra_vars: "{{ {'tripleo_backup_and_restore_nfs_server': '192.168.24.1'} | to_json }}"
      assert:
        that:
          - tripleo_undercloud_backup_result.stdout == 'undercloud backup --setup-rear --extra-vars {{ tripleo_undercloud_backup_extra_vars  }}'
