---
# tasks file for tripleo_overcloud_upgrade_run
- name: Setup overcloud upgrade run facts
  set_fact:
    _run_cmd: >-
      {{ tripleo_overcloud_upgrade_run_os_cloud | ternary('', "source " ~ tripleo_overcloud_upgrade_run_rc_file ~ "; ") }}
      {{ openstack_bin }} overcloud upgrade run
      {{ tripleo_overcloud_upgrade_run_limit | ternary('--limit $UPGRADE_LIMIT', '') }}
      {{ tripleo_overcloud_upgrade_run_playbook | tripleo.operator.shell_arg_list('--playbook') }}
      {{ tripleo_overcloud_upgrade_run_ssh_user | ternary('--ssh-user $UPGRADE_SSH_USER', '') }}
      {{ tripleo_overcloud_upgrade_run_static_inventory | ternary('--static-inventory $UPGRADE_STATIC_INVENTORY', '') }}
      {{ tripleo_overcloud_upgrade_run_tags | ternary('--tags $UPGRADE_TAGS', '') }}
      {{ tripleo_overcloud_upgrade_run_skip_tags | ternary('--skip-tags $UPGRADE_SKIP_TAGS', '') }}
      {{ tripleo_overcloud_upgrade_run_stack | ternary('--stack $UPGRADE_STACK', '') }}
      {{ tripleo_overcloud_upgrade_run_log_output | ternary((">" ~ tripleo_overcloud_upgrade_run_log), '') }}
      {{ tripleo_overcloud_upgrade_run_log_combine | ternary("2>&1", '') }}
    _run_env:
      UPGRADE_LIMIT: "{{ tripleo_overcloud_upgrade_run_limit | quote }}"
      UPGRADE_PLAYBOOK: "{{ tripleo_overcloud_upgrade_run_playbook| list | join(' ') }}"
      UPGRADE_SSH_USER: "{{ tripleo_overcloud_upgrade_run_ssh_user }}"
      UPGRADE_STATIC_INVENTORY: "{{ tripleo_overcloud_upgrade_run_static_inventory }}"
      UPGRADE_TAGS: "{{ tripleo_overcloud_upgrade_run_tags }}"
      UPGRADE_SKIP_TAGS: "{{ tripleo_overcloud_upgrade_run_skip_tags }}"
      UPGRADE_STACK: "{{ tripleo_overcloud_upgrade_run_stack }}"
      OS_CLOUD: "{{ tripleo_overcloud_upgrade_run_os_cloud }}"

- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ tripleo_overcloud_upgrade_run_log }}"
  when: tripleo_overcloud_upgrade_run_log_output|bool

- name: Show debug information
  when: tripleo_overcloud_upgrade_run_debug|bool
  block:
    - name: Show the overcloud upgrade run command
      debug:
        var: _run_cmd

    - name: Show the overcloud upgrade run environment
      debug:
        var: _run_env

- name: Write reproducer script
  tripleo_shell_script:
    dest: "{{ tripleo_overcloud_upgrade_run_home_dir }}/tripleo_overcloud_upgrade_run_ansible.sh"
    shell_command: "{{ _run_cmd }}"
    shell_environment: "{{ _run_env }}"
  when: tripleo_overcloud_upgrade_run_generate_scripts|bool

- name: Overcloud upgrade run
  shell: "{{ _run_cmd }}"  # noqa 305
  environment: "{{ _run_env }}"
  args:
    chdir: "{{ tripleo_overcloud_upgrade_run_home_dir }}"
    warn: false
  register: tripleo_overcloud_upgrade_run_result
  async: "{{ tripleo_overcloud_upgrade_run_timeout }}"
  poll: "{{ tripleo_overcloud_upgrade_run_poll }}"
  changed_when: false
  when:
    - not ansible_check_mode|bool
    - not tripleo_overcloud_upgrade_run_generate_scripts_only|bool

- name: Set output fact
  when:
    - tripleo_overcloud_upgrade_run_result.stdout is defined
  set_fact:
    tripleo_overcloud_upgrade_run_output: "{{ tripleo_overcloud_upgrade_run_result.stdout }}"
