# defaults file for tripleo_overcloud_node_provide
---
openstack_bin: openstack
tripleo_overcloud_node_provide_all_manageable: false
tripleo_overcloud_node_provide_debug: false
tripleo_overcloud_node_provide_home_dir: "{{ ansible_env.HOME }}"
tripleo_overcloud_node_provide_log: "{{ tripleo_overcloud_node_provide_home_dir }}/overcloud_node_provide.log"
tripleo_overcloud_node_provide_log_combine: true
tripleo_overcloud_node_provide_log_output: true
tripleo_overcloud_node_provide_node_uuids: []
tripleo_overcloud_node_provide_os_cloud: "{{ tripleo_os_cloud | default('') }}"
tripleo_overcloud_node_provide_poll: 1
tripleo_overcloud_node_provide_rc_file: "{{ tripleo_rc_file | default(ansible_env.HOME ~ '/stackrc') }}"
tripleo_overcloud_node_provide_timeout: 600
