---
# tasks file for tripleo_overcloud_external_update_run
- name: Setup overcloud external-update run facts
  set_fact:
    _update_run_cmd: >-
      {{ tripleo_overcloud_external_update_run_os_cloud | ternary('', "source " ~ tripleo_overcloud_external_update_run_rc_file ~ "; ") }}
      {{ openstack_bin }} overcloud external-update run
      {{ tripleo_overcloud_external_update_run_extra_vars | tripleo.operator.shell_arg_list('--extra-vars') }}
      {{ tripleo_overcloud_external_update_run_ssh_user | ternary('--ssh-user $UPDATE_SSH_USER', '') }}
      {{ tripleo_overcloud_external_update_run_tags | ternary('--tags $UPDATE_TAGS', '') }}
      {{ tripleo_overcloud_external_update_run_skip_tags | ternary('--skip-tags $UPDATE_SKIP_TAGS', '') }}
      {{ tripleo_overcloud_external_update_run_static_inventory | ternary('--static-inventory $UPDATE_STATIC_INVENTORY', '') }}
      {{ tripleo_overcloud_external_update_run_stack | ternary('--stack $UPDATE_STACK', '') }}
      {{ tripleo_overcloud_external_update_run_yes | ternary('--yes', '') }}
      {{ tripleo_overcloud_external_update_run_log_output | ternary((">" ~ tripleo_overcloud_external_update_run_log), '') }}
      {{ tripleo_overcloud_external_update_run_log_combine | ternary("2>&1", '') }}
    _update_run_env:
      OS_CLOUD: "{{ tripleo_overcloud_external_update_run_os_cloud }}"
      UPDATE_SSH_USER: "{{ tripleo_overcloud_external_update_run_ssh_user }}"
      UPDATE_TAGS: "{{ tripleo_overcloud_external_update_run_tags | quote }}"
      UPDATE_SKIP_TAGS: "{{ tripleo_overcloud_external_update_run_skip_tags | quote }}"
      UPDATE_STATIC_INVENTORY: "{{ tripleo_overcloud_external_update_run_static_inventory }}"
      UPDATE_STACK: "{{ tripleo_overcloud_external_update_run_stack }}"

- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ tripleo_overcloud_external_update_run_log }}"
  when: tripleo_overcloud_external_update_run_log_output|bool

- name: Show debug information
  when: tripleo_overcloud_external_update_run_debug|bool
  block:
    - name: Show the overcloud external-update run command
      debug:
        var: _update_run_cmd

    - name: Show the overcloud external-update run environment
      debug:
        var: _update_run_env

- name: Write reproducer script
  tripleo_shell_script:
    dest: "{{ tripleo_overcloud_external_update_run_home_dir }}/tripleo_overcloud_external_update_run.sh"
    shell_command: "{{ _update_run_cmd }}"
    shell_environment: "{{ _update_run_env }}"
  when: tripleo_overcloud_external_update_run_generate_scripts|bool

- name: Overcloud external-update run
  shell: "{{ _update_run_cmd }}"  # noqa 305
  environment: "{{ _update_run_env }}"
  args:
    chdir: "{{ tripleo_overcloud_external_update_run_home_dir }}"
    warn: false
  register: tripleo_overcloud_external_update_run_result
  async: "{{ tripleo_overcloud_external_update_run_timeout }}"
  poll: "{{ tripleo_overcloud_external_update_run_poll }}"
  changed_when: false
  when:
    - not ansible_check_mode|bool
    - not tripleo_overcloud_external_update_run_generate_scripts_only|bool

- name: Set output fact
  when:
    - tripleo_overcloud_external_update_run_result.stdout is defined
  set_fact:
    tripleo_overcloud_external_update_run_output: "{{ tripleo_overcloud_external_update_run_result.stdout }}"
