---
- name: Converge
  hosts: all
  collections:
    - tripleo.operator
  vars:
    openstack_bin: echo
    tripleo_os_cloud: undercloud
    tripleo_ceph_spec_run_debug: true
  tasks:

    - name: Call tripleo_ceph_spec role for standlone
      include_role:
        name: "tripleo_ceph_spec"
      vars:
        tripleo_ceph_spec_standalone: true
        tripleo_ceph_spec_mon_ip: 192.168.122.42
        tripleo_ceph_spec_file: /home/zuul/ceph_spec.yaml

    - name: Show result tripleo_ceph_spec_result
      debug:
        msg: "{{ tripleo_ceph_spec_result }}"

    - name: Assert tripleo_ceph_spec command for standalone
      assert:
        that:
          - tripleo_ceph_spec_result.stdout ==
            "overcloud ceph spec --standalone --mon-ip 192.168.122.42 --output /home/zuul/ceph_spec.yaml"
