---
openstack_bin: openstack
tripleo_ceph_user_become: false
tripleo_ceph_user_debug: false
tripleo_ceph_user_enable: true
tripleo_ceph_user_fsid:
tripleo_ceph_user_generate_scripts: "{{ tripleo_generate_scripts | default(False) }}"
tripleo_ceph_user_generate_scripts_only: "{{ tripleo_generate_scripts_only | default(False) }}"
tripleo_ceph_user_poll: 10
tripleo_ceph_user_spec: "{{ ansible_env.HOME }}/ceph_spec.yaml"
tripleo_ceph_user_ssh_user: ceph-admin
tripleo_ceph_user_stack:
tripleo_ceph_user_standalone: false
tripleo_ceph_user_timeout: 5700
tripleo_ceph_user_timeout_arg: 90
tripleo_ceph_user_working_dir:
