---
# tasks file for tripleo_overcloud_cell_export
- name: Set overcloud cell export facts
  set_fact:
    _export_cmd: >-
      {{ tripleo_overcloud_cell_export_os_cloud | ternary('', "source " ~ tripleo_overcloud_cell_export_rc_file ~ "; ") }}
      {{ openstack_bin }} overcloud cell export
      {{ tripleo_overcloud_cell_export_control_plane_stack | ternary('--control-plane-stack $EXPORT_CONTROL_STACK', '') }}
      {{ tripleo_overcloud_cell_export_cell_stack | ternary('--cell-stack $EXPORT_CELL_STACK', '') }}
      {{ tripleo_overcloud_cell_export_output_file | ternary('--output-file $EXPORT_OUTPUT_FILE', '') }}
      {{ tripleo_overcloud_cell_export_force_overwrite | ternary('--force-overwrite', '') }}
      {{ tripleo_overcloud_cell_export_name }}
      {{ tripleo_overcloud_cell_export_log_output | ternary((">" ~ tripleo_overcloud_cell_export_log), '') }}
      {{ tripleo_overcloud_cell_export_log_combine | ternary("2>&1", '') }}
    _export_env:
      EXPORT_CONTROL_STACK: "{{ tripleo_overcloud_cell_export_control_plane_stack | quote }}"
      EXPORT_CELL_STACK: "{{ tripleo_overcloud_cell_export_cell_stack | quote }}"
      EXPORT_OUTPUT_FILE: "{{ tripleo_overcloud_cell_export_output_file | quote }}"
      OS_CLOUD: "{{ tripleo_overcloud_cell_export_os_cloud }}"


- name: Preserve existing log file if exists
  timestamp_file:
    path: "{{ tripleo_overcloud_cell_export_log }}"
  when: tripleo_overcloud_cell_export_log_output|bool

- name: Show debug information
  when: tripleo_overcloud_cell_export_debug|bool
  block:
    - name: Show the command
      debug:
        var: _export_cmd

    - name: Show the environment
      debug:
        var: _export_env

- name: Write reproducer script
  tripleo_shell_script:
    dest: "{{ tripleo_overcloud_cell_export_home_dir }}/tripleo_overcloud_cell_export.sh"
    shell_command: "{{ _export_cmd }}"
    shell_environment: "{{ _export_env }}"
  when: tripleo_overcloud_cell_export_generate_scripts|bool

- name: Run overcloud cell export
  shell: "{{ _export_cmd }}"  # noqa 305
  environment: "{{ _export_env }}"
  args:
    executable: /bin/bash
    chdir: "{{ tripleo_overcloud_cell_export_home_dir }}"
    warn: false
  register: tripleo_overcloud_cell_export_result
  async: "{{ tripleo_overcloud_cell_export_timeout }}"
  poll: "{{ tripleo_overcloud_cell_export_poll }}"
  changed_when: false
  when:
    - not ansible_check_mode|bool
    - not tripleo_overcloud_cell_export_generate_scripts_only|bool

- name: Set output fact
  when:
    - tripleo_overcloud_cell_export_result.stdout is defined
  set_fact:
    tripleo_overcloud_cell_export_output: "{{ tripleo_overcloud_cell_export_result.stdout }}"
