---
- name: Converge
  hosts: all
  collections:
    - tripleo.operator
  vars:
    openstack_bin: echo
    tripleo_os_cloud: undercloud
    tripleo_undercloud_install_debug: true
    tripleo_undercloud_install_log_output: false
    tripleo_undercloud_install_log_combine: false
    tripleo_undercloud_install_poll: 1
  tasks:

    - name: "Include tripleo_undercloud_install"
      include_role:
        name: "tripleo_undercloud_install"

    - name: Check role
      assert:
        that:
          - tripleo_undercloud_install_result.stdout == "undercloud install"

    - name: Check parameter "tripleo_undercloud_install_force_stack_update"
      include_role:
        name: "tripleo_undercloud_install"
      vars:
        tripleo_undercloud_install_force_stack_update: true

    - name: Assert "tripleo_undercloud_install_force_stack_update"
      assert:
        that:
          - tripleo_undercloud_install_result.stdout == "undercloud install --force-stack-update"

    - name: Check parameter "tripleo_undercloud_install_no_validations"
      include_role:
        name: "tripleo_undercloud_install"
      vars:
        tripleo_undercloud_install_no_validations: true

    - name: Assert "tripleo_undercloud_install_no_validations"
      assert:
        that:
          - tripleo_undercloud_install_result.stdout == "undercloud install --no-validations"

    - name: Check parameter "tripleo_undercloud_install_inflight_validations"
      include_role:
        name: "tripleo_undercloud_install"
      vars:
        tripleo_undercloud_install_inflight_validations: true

    - name: Assert "tripleo_undercloud_install_inflight_validations"
      assert:
        that:
          - tripleo_undercloud_install_result.stdout == "undercloud install --inflight-validations"

    - name: Check parameter "tripleo_undercloud_install_dry_run"
      include_role:
        name: "tripleo_undercloud_install"
      vars:
        tripleo_undercloud_install_dry_run: true

    - name: Assert "tripleo_undercloud_install_dry_run"
      assert:
        that:
          - tripleo_undercloud_install_result.stdout == "undercloud install --dry-run"

    - name: Check parameter "tripleo_undercloud_install_yes"
      include_role:
        name: "tripleo_undercloud_install"
      vars:
        tripleo_undercloud_install_yes: true

    - name: Assert "tripleo_undercloud_install_yes"
      assert:
        that:
          - tripleo_undercloud_install_result.stdout == "undercloud install --yes"

    - name: Check parameter "tripleo_undercloud_install_reproducer_command"
      include_role:
        name: "tripleo_undercloud_install"
      vars:
        tripleo_undercloud_install_reproducer_command: true

    - name: Assert "tripleo_undercloud_install_reproducer_command"
      assert:
        that:
          - tripleo_undercloud_install_result.stdout == "undercloud install --reproduce-command"
