---
# tasks file for tripleo_overcloud_node_introspect
- name: Setup overcloud node introspect command
  set_fact:
    _introspect_cmd: >-
      {{ tripleo_overcloud_node_introspect_os_cloud | ternary('', "source " ~ tripleo_overcloud_node_introspect_rc_file ~ "; ") }}
      {{ openstack_bin }} overcloud node introspect
      {{ tripleo_overcloud_node_introspect_node_uuids | join(' ') }}
      {{ tripleo_overcloud_node_introspect_all_manageable | ternary('--all-manageable', '') }}
      {{ tripleo_overcloud_node_introspect_provide | ternary('--provide', '') }}
      {{ tripleo_overcloud_node_introspect_run_validations | ternary('--run-validations', '') }}
      {{ tripleo_overcloud_node_introspect_node_timeout | ternary('--node-timeout ' ~ tripleo_overcloud_node_introspect_node_timeout, '') }}
      {{ tripleo_overcloud_node_introspect_max_retries | ternary('--max-retries ' ~ tripleo_overcloud_node_introspect_max_retries, '') }}
      {{ tripleo_overcloud_node_introspect_retry_timeout | ternary('--retry-timeout ' ~ tripleo_overcloud_node_introspect_retry_timeout, '') }}
      {{ tripleo_overcloud_node_introspect_concurrency | ternary('--concurrency ' ~ tripleo_overcloud_node_introspect_concurrency, '') }}
    _introspect_env:
      OS_CLOUD: "{{ tripleo_overcloud_node_introspect_os_cloud }}"

- name: Show debug information
  when: tripleo_overcloud_node_introspect_debug|bool
  block:
    - name: Show the node introspect command
      debug:
        var: _introspect_cmd

    - name: Show the node introspect environment
      debug:
        var: _introspect_env

- name: Write reproducer script
  tripleo_shell_script:
    dest: "{{ tripleo_overcloud_node_introspect_home_dir }}/tripleo_overcloud_node_introspect.sh"
    shell_command: "{{ _introspect_cmd }}"
    shell_environment: "{{ _introspect_env }}"
  when: tripleo_overcloud_node_introspect_generate_scripts|bool

- name: Introspect node
  shell: "{{ _introspect_cmd }}"  # noqa 305
  environment: "{{ _introspect_env }}"
  register: tripleo_overcloud_node_introspect_result
  changed_when: true
  when: not tripleo_overcloud_node_introspect_generate_scripts_only|bool

- name: Set output fact
  when:
    - tripleo_overcloud_node_introspect_result.stdout is defined
  set_fact:
    tripleo_overcloud_node_introspect_output: "{{ tripleo_overcloud_node_introspect_result.stdout }}"
