---
- name: Converge
  hosts: all
  collections:
    - tripleo.operator
  vars:
    openstack_bin: echo
    tripleo_os_cloud: undercloud
    tripleo_ceph_deploy_run_debug: true
  tasks:

    - name: Call tripleo_ceph_deploy role for standlone
      include_role:
        name: "tripleo_ceph_deploy"
      vars:
        tripleo_ceph_deploy_standalone: true
        tripleo_ceph_deploy_mon_ip: 192.168.122.42
        tripleo_ceph_deploy_spec: /home/zuul/ceph_spec.yaml
        tripleo_ceph_deploy_stack: standalone
        tripleo_ceph_deploy_output: /home/zuul/deployed_ceph.yaml

    - name: Show result tripleo_ceph_deploy_result
      debug:
        msg: "{{ tripleo_ceph_deploy_result }}"

    - name: Assert tripleo_ceph_deploy command for standalone
      assert:
        that:
          - tripleo_ceph_deploy_result.stdout ==
            "overcloud ceph deploy --output /home/zuul/deployed_ceph.yaml --standalone --mon-ip 192.168.122.42 --ceph-spec /home/zuul/ceph_spec.yaml --stack standalone --cephadm-ssh-user ceph-admin"
