---
- name: Setup validator list facts
  set_fact:
    _validator_list_cmd: >-
      {{ openstack_bin }} tripleo validator list

- name: Show debug information
  when:
    tripleo_validator_list_debug|bool
  block:
    - name: Show validator list command
      debug:
        var: _validator_list_cmd

- name: List validation(s)
  shell: "{{ _validator_list_cmd }}"
  register: tripleo_validator_list_result
  changed_when: true
