# defaults file for tripleo_overcloud_container_image_build
---
openstack_bin: openstack
tripleo_overcloud_container_image_build_config_files: []
tripleo_overcloud_container_image_build_debug: false
tripleo_overcloud_container_image_build_excludes: []
tripleo_overcloud_container_image_build_generate_scripts: "{{ tripleo_generate_scripts | default(False) }}"
tripleo_overcloud_container_image_build_generate_scripts_only: "{{ tripleo_generate_scripts_only | default(False) }}"
tripleo_overcloud_container_image_build_home_dir: "{{ ansible_env.HOME }}"
tripleo_overcloud_container_image_build_kolla_config_file:
tripleo_overcloud_container_image_build_list_dependencies: false
tripleo_overcloud_container_image_build_list_images: false
tripleo_overcloud_container_image_build_log: "{{ tripleo_overcloud_container_image_build_home_dir }}/overcloud_container_image_build.log"
tripleo_overcloud_container_image_build_log_combine: true
tripleo_overcloud_container_image_build_log_output: true
tripleo_overcloud_container_image_build_poll: 10
tripleo_overcloud_container_image_build_timeout: 3600
tripleo_overcloud_container_image_build_use_buildah: false
tripleo_overcloud_container_image_build_work_dir:
